
// Users Actions
export const ADD_USERS_TO_NEARBY_USERS_LIST = 'ADD_USERS_TO_NEARBY_USERS_LIST';
export const REFRESH_NEARBY_USERS_LIST = 'REFRESH_NEARBY_USERS_LIST';
export const SET_HAS_LOADED_ALL_NEARBY_USERS = 'SET_HAS_LOADED_ALL_NEARBY_USERS';
